--- #YAML:1.0
name:               Unicode-Casing
version:            0.12
abstract:           Perl extension to override system case changing functions
author:
    - Karl Williamson <khw@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    B::Hooks::OP::Check:  0
    B::Hooks::OP::PPAddr:  0
    ExtUtils::Depends:    0
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    B::Hooks::OP::Check:  0
    B::Hooks::OP::PPAddr:  0
    Test::More:           0
    XSLoader:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
